### ISSUE TITLE
NSD 4.3.1 - make test fails

### ISSUE THREAD

**Issue by mgiacomoli** [NLnetLabs/nsd#98]
Just downloaded last 4.3.1 tarball from your site.
The host is an Ubuntu server 18.04, and I already built successfully nsd 4.2.4 on this server.
./configure -> ok
make -> ok
make test -> returns me this error:
`make: *** No rule to make target 'tpkg/cutest/cutest_dname.c', needed by 'cutest_dname.o'.  Stop.`

And yes, I'm sure I run `make test`

Let me know if you need additional info

**Comment by wcawijngaards** [comment]
Yes this has already been fixed in #95  Removed make test check because tpkg not included in release tarballs.  The test code is not included in a release, source code checkouts have them, but we remove it from the production release tarballs.

**Comment by mgiacomoli** [comment]
Ok, thank you for your clarification, but `test` target is still present in generated Makefile and could cause confusion, as it happened to me. Just a suggestion

**Comment by wcawijngaards** [comment]
Okay, yes, very much so, and that suggestion has already been applied, but is not yet in the released version of NSD.  It is scheduled for future releases, from the commit in #95.  That removes the make test target, it would print something like unknown target "test" or so as an error.
